spring:
  application:
    name: email-service
  mvc:
    servlet:
      path: /email-service # // localhost:8080/user-service/user <- this /user is controller pattern


server:
  port: 0   # means let eureka decide which port

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka #eruka's location

