spring:
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: anita.sj.chen@gmail.com
    password: e53df69385378cc5e5f1beed8e39b3ecec03b51e00057d88948ce346488973d90a1843f5c904abc876a4ef65962e5e02
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    from: anita.sj.chen@gmail.com

app:
  mail:
    sender-name: HR Onboarding System

jwt:
  secret: hr-onboarding
  expiration: 3600000

server:
  port: 9004

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

