spring:
  application:
    name: employee-service
  data:
    mongodb:
      uri: mongodb+srv://admin:JoTE7Horkdl4YwbP@cluster0.y5de1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: "HR_OnBoarding_System"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
server:
  port: 9001

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

