spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: housing-service
          uri: lb://housing-service
          predicates:
            - Path=/housing-service/**
        - id: composite-service
          uri: lb://composite-service
          predicates:
            - Path=/composite-service/**

server:
  port: 9000 # can have a fix server port

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
