spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173" 
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"                       
            allowCredentials: true
            
      routes:
        - id: employee-service
          uri: lb://employee-service  # service name
          predicates:
            - Path=/employees/**

        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/applications/**, /documents/**

        - id: housing-service
          uri: lb://housing-service
          predicates:
            - Path=/housing/**

        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email/**

        - id: auth-service
          uri: http://localhost:9005  # static URL for the auth service
          predicates:
            - Path=/auth/**

server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
